# Configuration for the C2 server

server:
  http_port: "7777" # Port for the HTTP server
  https_port: "8888" # Port for the HTTPS server
  read_timeout: "15s" # maximum duration for reading the entire request, including the body
  write_timeout: "15s" # Maximum duration before timing out writes of the response
  idle_timeout: "60s" # Maximum amount of time to wait for the next request
  max_header_bytes: 1048576 # Maximum size of request headers in bytes (1 MB)

logging:
  level: "INFO" # log level: DEBUG, INFO, WARN, ERROR

security:
  jwt_secret: "mysecretkey" # Secret key used forf JWT authentication
  encryption_key: "myencryptionkey" # Used for encrypting sensitive data
  tls_cert_file: "/path/to/your/cert.pem" # Path to your TLS certificate file for HTTPS
  tls_key_file: "/path/to/your/key.pem" # Path to the TLS key file for HTTPS

database:
  url: postgres://user:password@localhost:5432/c2db?sslmode=disable # URL for the database connection

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://my-frontend.com"

api:
  version: "v1" # API versioning
  default_agent_group: "default" # Default group for newly registered agents